export { default as Menu } from './Menu';
export { default as Social } from './Social';
export { default as Side } from './Side';
export { default as Email } from './Email';
export { default as Hero } from './Hero';
export { default as About } from './About';
export { default as Featured } from './Featured';
export { default as Projects } from './Projects';
export { default as Contact } from './Contact';
export * from './Icons';
